### ISSUE TITLE
Stuck at loading config file step

### ISSUE THREAD

**Issue by JiDai** [michael-ciniawsky/postcssrc-cli#1]
Hi!

Here is my command : 
```
/node_modules/.bin/postcss --output=layout.css
```

Here is my config files `postcss.config.js`

```
module.exports = (ctx) => {
    return {
        map: ctx.env === 'development' ? 'inline' : false,
        plugins: {
            'autoprefixer': {
                'browsers': ['last 2 versions', 'ie > 8', 'iOS 8']
            },
            'cssnano': ctx.env !== 'development' ? {} : false
        }
    }
}
```

In the output I have `⠹ Loading Config` and anything else happens

**Comment by michael-ciniawsky** [comment]
You mean the spinner `⠹ Loading Config` doesn't stop? :)

**Comment by JiDai** [comment]
Yes :)

**Comment by michael-ciniawsky** [comment]
👍  made a note, will be fix it with other bugs in the pipeline :)

**Comment by tbremer** [comment]
@JiDai, I had a similar issue and was able to get past it with this command:

```bash
$ node_modules/.bin/postcss --dir ./ --config postcss.config.js src/web/css/app.css -o dist/style.css --watch
```

**Comment by michael-ciniawsky** [comment]
@JiDai @tbremer Keep an eye on postcss-cli#develop (v3) which should be released soon. Notify bc and I will retire this repo shortly after that release

![postcss-cli-err](https://cloud.githubusercontent.com/assets/5419992/21965445/2e358156-db60-11e6-9d09-6e00415d6248.png)
